SET NOCOUNT ON;
select
    AH_PK,
    AH_Ledger,
    AH_TransactionType,
REPLACE(replace(replace(replace(replace(AH_TransactionNum, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as AH_TransactionNum,    
AH_TransactionCount,
    AH_TransactionReference,
    REPLACE(replace(replace(replace(replace(AH_Desc, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as AH_Desc,
    AH_InvoiceDate,
    AH_TransactionCategory,
    AH_DueDate,
    AH_InvoiceAmount,
    AH_GSTAmount,
    AH_WithholdingTax,
    AH_OSTotal,
    AH_ExchangeRate,
    AH_AgePeriod,
    AH_PostPeriod,
    AH_PostDate,
REPLACE(replace(replace(replace(replace(AH_ChequeOrReference, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as AH_ChequeOrReference,
    AH_ReceiptType,
REPLACE(replace(replace(replace(replace(AH_ChequeDrawer, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as AH_ChequeDrawer ,    
REPLACE(replace(replace(replace(replace(AH_DrawerBank, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as AH_DrawerBank ,
    AH_DrawerBranch ,
    AH_ConsolidatedInvoiceRef,
    AH_FullyPaidDate,
    AH_DateClearedInCashbook,
    AH_OutstandingAmount,
    AH_PostToGL,
    AH_ReceiptBatchNo,
    AH_InvoiceTerm,
    AH_InvoiceTermDays,
    AH_ExportBatchNumber,
    AH_AB,
    AH_OH,
    AH_JH,
    AH_GB,
    AH_GE,
    AH_AG,
    AH_TransactionBelongsToGroup,
    AH_AH_InvoiceStatement,
    AH_GC,
    AH_RX_NKTransactionCurrency,
    AH_RequisitionDate,
    AH_RequisitionStatus,
    AH_SystemCreateTimeUtc,
    AH_SystemCreateUser,
    AH_NumberOfSupportingDocuments,
    AH_ComplianceSubType,
    AH_SystemLastEditTimeUtc,
    AH_SystemLastEditUser,
    AH_OC_InvoiceContactOverride,
    AH_OA_InvoiceAddressOverride,
    AH_SubClassParentTableCode,
    AH_SubClassParentId,
    AH_CashBasisGSTIndicator,
    AH_CashBasisGSTRealisedToGL,
    AH_InvoiceApproved,
    AH_InvoicePrinted,
    AH_IsCancelled,
    AH_NotAllocated,
    AH_PostedToEFT,
    AH_TransactionCreatedByMatching,
    AH_PostedInternal,
    AH_POST1,
    AH_POST2,
    AH_POST3,
    AH_POST4,
    AH_AgreedPaymentMethodOverride,
    AH_ComplianceDocumentDate,
    AH_GS_NKAuditedBy,
    AH_GS_NKCashier,
    AH_InvoicePaymentReferenceCode,
    AH_DigitalSignature_COMPRESSED,
    AH_LocalTaxAmountOtherTaxes,
    AH_OSTaxAmountOtherTaxes,
    AH_PlaceOfSupply,
    AH_PlaceOfSupplyType
from dbo.AccTransactionHeader;