set nocount on;
select
	GC_PK,
	GC_Code,
    REPLACE(replace(replace(replace(replace(GC_Name, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as GC_Name,
	GC_BusinessRegNo,
	GC_BusinessRegNo2,
	GC_CustomsRegistrationNo,
	GC_Address1,
	GC_Address2,
	GC_City,
	GC_Phone,
	GC_PostCode,
	GC_State,
	GC_Fax,
	GC_WebAddress,
	GC_NoOfAccountingPeriods,
	GC_PeriodFormat,
	GC_StartDate,
	GC_PeriodEndWeekDay,
	GC_GLCurrentPeriod,
	GC_ARAPCurrentPeriod,
	GC_GLClosedPeriod,
	GC_ARAPClosedPeriod,
	GC_OH_OrgProxy,
	GC_ExRateDisplayMode,
	GC_ExRateDecimals,
	GC_RX_NKLocalCurrency,
	GC_RN_NKCountryCode ,
	GC_LocalDocLanguage ,
	GC_IsValid,
	GC_IsGSTRegistered,
	GC_IsGSTCashBasis,
	GC_IsWHTRegistered,
	GC_IsWHTCashBasis,
	GC_IsReciprocal,
	GC_IsActive,
	GC_Email,
	GC_AddressMap,
	GC_ValidationStatus 
from dbo.GlbCompany;