SET NOCOUNT ON;
select
	GS_PK,
	GS_LoginName,
	GS_Password ,
	GS_EmploymentBasis,
	GS_NameTitle,
REPLACE(replace(replace(replace(replace(GS_FullName, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as GS_FullName,
	GS_NameSuffix,
REPLACE(replace(replace(replace(replace(GS_FriendlyName, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as GS_FriendlyName,
REPLACE(replace(replace(replace(replace(GS_UserAddress1, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as GS_UserAddress1,
	GS_UserAddress2,
	GS_City,
	GS_State,
	GS_Postcode,
REPLACE(replace(replace(replace(replace(GS_Title, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as GS_Title,
	GS_WorkPhone ,
	GS_WorkExtension,
	GS_HomePhone,
	GS_MobilePhone,
	GS_Pager ,
	GS_FaxNum ,
	GS_Birthdate,
	GS_WagesBankName,
	GS_WagesBankAccount,
	GS_WagesBankBsb,
	GS_WagesBankSwift,
	GS_NextOfKin,
	GS_NextOfKinHomePhone,
	GS_NextOfKinWorkPhone,
	GS_EmergencyContactName,
	GS_EmergencyHomePhone,
	GS_EmergencyWorkPhone,
	GS_EmploymentDate,
	GS_DepartureDate,
	GS_DueBack,
	GS_OutOnTask,
	GS_PersonalEDIMailBox,
	GS_BrokerID,
	GS_BrokerPassword,
	GS_BrokerWorkingPassword,
	GS_Passport,
	GS_PasswordReuseScratch ,
	GS_LastPasswordChangeDate,
	GS_NextReviewDate,
	GS_GB_HomeBranch ,
	GS_GE_HomeDepartment,
	GS_WorkingLanguage,
	GS_ResourceType,
	GS_SecurityCardNumber,
	GS_EnterpriseCertificationID,
	GS_LastActivityDate,
	GS_CommissionBasis,
	GS_NewClientCommissionRate,
	GS_EstablishedClientCommissionRate,
	GS_CommissionMinimumEarning,
	GS_NextOfKinRelationship,
	GS_EmergencyContactRelationship,
	GS_LastPasswordAttemptDateTime_UTC,
	GS_IsActivityLogged,
	GS_Gender,
	GS_ActiveDirectoryObjectGuid,
	GS_SystemCreateTimeUtc,
	GS_SystemCreateUser,
	GS_SystemLastEditTimeUtc,
	GS_SystemLastEditUser,
	GS_IsSalesRep,
	GS_IsController,
	GS_IsSystemAccount,
	GS_IsDeveloper,
	GS_IsBackupOperator,
	GS_IsReadOnlyDBUser,
	GS_IsValid,
	GS_PublishWorkPhone,
	GS_PublishWorkExtension,
	GS_PublishHomePhone,
	GS_PublishMobilePhone,
	GS_IsActive,
	GS_PublishFaxNum,
	GS_PublishEmailAddress,
	GS_EftWages,
	GS_IsResource,
	GS_IsInTrainingMode ,
	GS_ChangePasswordAtNextLogin,
	GS_PasswordNeverChanges,
	GS_Code,
	REPLACE(replace(replace(replace(replace(GS_EmailAddress, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as GS_EmailAddress,
	GS_BrokerPasswordStatus,
	GS_AddressMap,
	GS_CanLogin,
	GS_GB_LastLogonBranch,
	GS_GC_PreferredPaymentCompany,
	GS_GE_LastLogonDepartment,
	GS_IsDatabaseDeveloper,
	GS_IsDevice,
	GS_IsOperational,
	GS_IsTwoFactorAuthenticationEnabled,
	GS_PER,
	GS_RN_NKCountryCode ,
	GS_ValidationStatus ,
	GS_RN_NKNationalityCode,
	GS_DomainName,
	GS_IsDriver,
	GS_ActivityTrackingStatus,
	GS_PasswordHash,
	GS_PasswordHashIterations,
	GS_PasswordSalt,
	GS_EmergencyContactEmail,
	GS_LastDayOfWork,
	GS_NextOfKinEmail,
	GS_ProbationEndDate,
	GS_ResidencyExpiry,
	GS_ResidencyStatus		
from dbo.GlbStaff;