set nocount on;
select
    JH_PK,
    JH_JobNum,
    JH_TH_NKQuoteNumber ,
    JH_Status ,
    JH_A_JOP ,
    JH_A_JCL ,
    JH_LocalChargesCFX,
    JH_AgentChargesCFX ,
    JH_LocalClientInvoicingStyle,
    JH_UniqueJobInvoiceNumber,
    JH_PaymentCollectionStatus,
    JH_GB,
    JH_GE,
    JH_GC,
    JH_SystemCreateTimeUtc,
    JH_SystemCreateUser,
    JH_SystemLastEditTimeUtc,
    JH_SystemLastEditUser,
    JH_ProfitShareInvoice,
    JH_JobPlannedStartDate,
    JH_JobBufferPercentOverride,
    JH_OC_LocalBillingContact,
    JH_RevenueRecognizedDate,
    JH_ParentID,
    JH_JH_ParentJob,
    JH_ProfitLossReasonCode,
    JH_OA_LocalChargesAddr ,
    JH_OA_AgentCollectAddr ,
    JH_GS_NKRepSales,
    JH_GS_NKRepOps ,
    JH_HeaderType ,
    JH_Name ,
    JH_Description,
    JH_JobLocalReference,
    JH_ARInvoiceReference,
    JH_IsProfitSharePosted ,
    JH_IsValid,
    JH_SingleAgentsInvoicePerConsol,
    JH_RatingHasBeenRun,
    JH_ExcludeFromPeriodicRating,
    JH_ParentTableCode,
    JH_HoldReason
from dbo.JobHeader;