set nocount on;
select
    JO_PK,
    JO_LineNo,
    JO_SubLineNo,
    JO_Partno ,
    JO_PartAttrib1,
    JO_PartAttrib2,
    JO_PartAttrib3,
    REPLACE(replace(replace(replace(replace(JO_Description, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as JO_Description,
    JO_Quantity ,
    JO_OrderUnitOfQty,
    JO_InnerPacks ,
    JO_OuterPacks ,
    JO_ActualVolume,
    JO_UnitOfVolume,
    JO_ActualWeight,
    JO_UnitOfWeight,
    JO_ItemPrice ,
    JO_LinePrice ,
    JO_LineDropDate,
    JO_QtyInvoiced,
    JO_QtyReceived,
    JO_LineStatus,
    JO_SpecialInstructions,
    JO_AdditionalInformation,
    JO_JD,
    JO_CustomAttrib1,
    JO_CustomAttrib2,
    JO_CustomAttrib3,
    JO_CustomAttrib4,
    JO_CustomAttrib5,
    JO_CustomAttrib6,
    JO_CustomTextBlob1,
    JO_CustomDate1,
    JO_CustomDate2,
    JO_CustomDate3,
    JO_CustomDate4,
    JO_CustomDate5,
    JO_CustomDecimal1,
    JO_CustomDecimal2,
    JO_CustomDecimal3,
    JO_CustomDecimal4,
    JO_CustomDecimal5,
    JO_OH_Supplier,
    JO_ContainerNumber,
    JO_ContainerPackingOrder,
    JO_RN_NKCountryOfOrigin,
    JO_CommercialInvoiceNo,
    JO_LineSplitNumber,
    JO_F3_NKPackType,
    JO_InnerPacksUQ,
    JO_OuterPacksUQ,
    JO_ItemPriceFactor,
    JO_INCO,
    JO_AdditionalTerms,
    JO_ConfirmationNum,
    JO_HSCode,
    JO_EANUPC,
    JO_ConfirmationDate,
    JO_ExWorksDate ,
    JO_OuterPackLength,
    JO_OuterPackHeight,
    JO_OuterPackWidth ,
    JO_OuterPackUnitOfDimension,
    JO_IsValid,
    JO_CustomFlag1,
    JO_CustomFlag2,
    JO_CustomFlag3,
    JO_CustomFlag4,
    JO_CustomFlag5
from  dbo.JobOrderLine;