set nocount on;
select
	JD_PK ,
	JD_FirstBuyerContact ,
	JD_SecondBuyerContact,
	JD_OrderNumber ,
	JD_OrderNumberSplit ,
	JD_OrderDate ,
	JD_OrderStatus,
	JD_OrderGoodsDescription,
	JD_TransportMode ,
	JD_ContainerMode ,
	JD_BookingConfRef,
	JD_BookingConfDate,
	JD_ExWorksRequiredBy,
	JD_DeliveryRequiredBy ,
	JD_QuoteNumber ,
	JD_InvoiceNumber,
	JD_InvoiceDate,
	JD_EstimatedExchangeRate,
	JD_RS_NKServiceLevel_NI ,
	JD_IncoTerm ,
	JD_AdditionalTerms,
	JD_RL_NKGoodsAvailableAt ,
	JD_RL_NKPortOfLoading ,
	JD_RL_NKPortOfDischarge ,
	JD_RL_NKGoodsDeliveredTo,
	JD_RV_NKDepartureVessel ,
	JD_DepartureVoyage ,
	JD_DepartureVesselCutoffDate,
	JD_RV_NKIntermediateVessel,
	JD_IntermediateVoyage ,
	JD_RV_NKArrivalVessel ,
	JD_ArrivalVoyage,
	JD_OH_Carrier ,
	JD_OH_SendingAgent ,
	JD_OH_ReceivingAgent ,
	JD_ActualVolume ,
	JD_UnitOfVolume ,
	JD_ActualWeight ,
	JD_UnitOfWeight ,
	JD_Waybill ,
	JD_MasterWaybill,
	JD_Packs ,
	JD_E_ARV_2ndIntermediate ,
	JD_E_ARV_1stIntermediate ,
	JD_E_DEP_2 ,
	JD_E_DEP_3 ,
	JD_EstimateUserDate1 ,
	JD_EstimateUserDate2 ,
	JD_EstimateUserDate3 ,
	JD_EstimateUserDate4 ,
	JD_ActualUserDate1 ,
	JD_ActualUserDate2 ,
	JD_ActualUserDate3 ,
	JD_ActualUserDate4 ,
	JD_FollowUpDate ,
	JD_CustomAttrib1 ,
	JD_CustomAttrib2 ,
	JD_CustomAttrib3 ,
	JD_CustomAttrib4 ,
	JD_CustomAttrib5 ,
	JD_CustomDate1 ,
	JD_CustomDate2 ,
	JD_CustomDecimal1 ,
	JD_CustomDecimal2 ,
	JD_CustomDecimal3 ,
	JD_CustomDecimal4 ,
	JD_CustomDecimal5 ,
	JD_SystemCreateTimeUtc,
	JD_SystemCreateUser ,
	JD_SystemLastEditTimeUtc,
	JD_SystemLastEditUser,
	JD_JS ,
	JD_JE ,
	JD_OrderType,
	JD_RN_NKCountryOfSupply ,
	JD_EF_ShipmentPrePlanning ,
	JD_RX_NKOrderCurrency,
	JD_F3_NKPackType,
	JD_IsValid,
	JD_IsCancelled ,
	JD_CustomFlag1 ,
	JD_CustomFlag2 ,
	JD_CustomFlag3 ,
	JD_CustomFlag4 ,
	JD_CustomFlag5 ,
	JD_OA_BuyerAddress ,
	JD_OA_SupplierAddress,
	JD_OC_BuyerContact ,
	JD_OC_SupplierContact
from dbo.JobOrderHeader