set nocount on;
select
	JL_PK,
	JL_FreightMode,
	JL_ItemNo,
	JL_EndItemNo,
	JL_PackageCount,
	JL_LinePrice,
	JL_Outturn ,
	JL_OutturnedLength,
	JL_OutturnedHeight,
	JL_OutturnedWidth ,
	JL_OutturnedWeight,
	JL_OutturnedVolume,
    REPLACE(replace(replace(replace(replace(JL_OutturnComment, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as JL_OutturnComment,
	JL_Pillaged,
	JL_Damaged,
	JL_ActualWeight,
	JL_ActualWeightUQ,
	JL_Length,
	JL_Height,
	JL_Width,
	JL_UnitOfDimension,
	JL_ActualVolume,
	JL_ActualVolumeUQ,
    REPLACE(replace(replace(replace(replace(JL_RefNumber, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as JL_RefNumber,
    REPLACE(replace(replace(replace(replace(JL_Description, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as JL_Description,
	JL_HarmonisedCode,
	JL_RN_NKOrigin,
	JL_RH_NKCommodityCode,
	REPLACE(replace(replace(replace(replace(JL_MarksAndNumbers, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as JL_MarksAndNumbers,
	JL_JS,
	JL_CustomAttrib1,
	JL_CustomAttrib2,
	JL_CustomAttrib3,
	JL_CustomAttrib4,
	JL_CustomDecimal1,
	JL_CustomDecimal2,
	JL_CustomDate1,
	JL_CustomDate2,
    REPLACE(replace(replace(replace(replace(JL_DetailedDescription, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as JL_DetailedDescription,
	JL_ContainerPackingOrder,
	JL_F3_NKPackType,
	JL_LoadingMeters,
	JL_IsValid,
	JL_CustomFlag1,
	JL_CustomFlag2,
	JL_ExportRefNumber,
	JL_ImportRefNumber,
	JL_VehicleColor,
	JL_VehicleMake,
	JL_VehicleModel,
	JL_VehicleNumberOfDoors,
	JL_VehicleTransmission,
	JL_VehicleYear
from dbo.JobPackLines;