set nocount on;
select
	OA_PK,
    REPLACE(replace(replace(replace(replace(OA_Code, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Code,
	REPLACE(replace(replace(replace(replace(OA_CompanyNameOverride, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_CompanyNameOverride,
    REPLACE(replace(replace(replace(replace(OA_Address1, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Address1,
    REPLACE(replace(replace(replace(replace(OA_Address2, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Address2,
	REPLACE(replace(replace(replace(replace(OA_City, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_City,
	REPLACE(replace(replace(replace(replace(OA_State, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_State,
    REPLACE(replace(replace(replace(replace(OA_PostCode, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_PostCode,
	REPLACE(replace(replace(replace(replace(OA_Phone, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Phone,
    REPLACE(replace(replace(replace(replace(OA_Fax, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Fax,
	REPLACE(replace(replace(replace(replace(OA_Mobile, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Mobile,
    REPLACE(replace(replace(replace(replace(OA_PickupFromTimeOnly, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_PickupFromTimeOnly,
	REPLACE(replace(replace(replace(replace(OA_PickupToTimeOnly, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_PickupToTimeOnly,
	REPLACE(replace(replace(replace(replace(OA_DeliverFromTimeOnly, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_DeliverFromTimeOnly,
	REPLACE(replace(replace(replace(replace(OA_DeliverToTimeOnly, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_DeliverToTimeOnly,
	OA_DoNotAttendFrom,
	OA_DoNotAttendTo,
	OA_ContainerHandling,
	OA_AccessPoint,
	REPLACE(replace(replace(replace(replace(OA_LabourRequired, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_LabourRequired,
	OA_CommunicationRequired,
	OA_Dock_Height,
	OA_FCLEquipmentNeeded,
	OA_LCLEquipmentNeeded,
	OA_AIREquipmentNeeded,
	OA_RL_NKRelatedPortCode,
	OA_OH,
	OA_IsValid,
	OA_DockLeveler,
	OA_ForkLift,
	OA_PalletJack,
	OA_IsActive,
	REPLACE(replace(replace(replace(replace(OA_Email, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_Email,
	REPLACE(replace(replace(replace(replace(OA_OtherWarehouseFacilities, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_OtherWarehouseFacilities,
	REPLACE(replace(replace(replace(replace(OA_LoadingUnloadingConstraints, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_LoadingUnloadingConstraints,
    	REPLACE(replace(replace(replace(replace(OA_AdditionalAddressInformation, CHAR(13), ''), CHAR(10), ''),',',''),'"',''),'''','') as OA_AdditionalAddressInformation,
    	OA_AddressMap,
	OA_AuthorityToLeave,
	OA_DeliveryRoute,
	OA_DeliveryRouteSequence,
    	OA_GroupNumber,
	OA_RN_NKCountryCode,
	OA_SuppressAddressValidationError,
	OA_UseCumulativeFreeWaitingTime,
	OA_ValidationStatus,
	OA_VerifiesContainerGrossWeight,
	OA_SystemCreateTimeUtc,
	OA_SystemCreateUser,
	OA_SystemLastEditTimeUtc,
	OA_SystemLastEditUser,
	OA_Language,
    OA_JobLoadingDuration
from dbo.OrgAddress;