set nocount on;
select 
	P9_PK ,
	P9_TaskID,
	P9_Sequence,
	P9_Type ,
	P9_Status ,
	P9_ScheduledDate,
	P9_EstDuration,
	P9_ActualDate ,
	P9_ActualDuration,
	P9_Notes,
	P9_GS_NKAssignedStaffMember ,
	P9_GG_AssignedGroup,
	P9_OA,
	P9_OC,
	P9_ParentID,
	P9_ParentTableCode ,
	P9_IsValid ,
	P9_SE_NKMilestoneEvent,
	P9_SE_NKTaskCompletionEvent ,
	P9_SE_NKExceptionEvent ,
	P9_MilestoneExceptionAdded,
	P9_IsCalendarItem ,
	P9_SuspendedAt ,
	P9_TotalSuspendedDuration ,
	P9_NonWorkHours ,
	P9_TaskCannotBeDeleted,
	P9_Condition1 ,
	P9_AndOr,
	P9_Condition2 ,
	P9_RN_NKOriginCountry,
	P9_RN_NKDestinationCountry,
	P9_ReferencedID,
	P9_IsPublished ,
	P9_EstimatedDefaultedFrom ,
	P9_EstimatedDefaultTimeDelta,
	P9_EstimatedDefaultFromPredecessor,
	P9_GC,
	P9_TriggerField,
	P9_ParentTemplateID,
	P9_ExceptionAddedUTC,
	P9_ScheduledDateUTC,
	P9_ActualDateUTC ,
	P9_SuspendedAtUTC ,
	P9_Condition2Value ,
	P9_EstimateVariationFactor ,
	P9_EstimatedTimeToComplete,
	P9_CompletedTimeUtc ,
	P9_RespondToCascadedEvents,
	P9_OriginalScheduledDateUtc ,
	P9_RecalculateScheduledDate ,
	P9_CascadedEventsContext ,
	P9_FH_ProcessHeader ,
	P9_IsInterruptable ,
	P9_G4_RequiredCapability ,
	P9_Description,
	P9_ReferencedTableCode ,
	P9_CardNote,
	P9_EstimatedHandoverTimeUtc ,
	P9_LineTriggerType ,
	P9_TriggerCondition ,
	P9_TriggerFiredCountdown,
	P9_GB_TriggerBranch ,
	P9_GB_TriggerDepartment ,
	P9_PenetrationResetDateUtc,
	P9_TriggerContext
from dbo.ProcessTasks;